version: '3'
services:
  webserver:
    build: node
    image: node-react
    container_name: node
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "4000:4000"
      - "4100:4100"
